# Generated by Django 4.1.6 on 2023-03-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('pic1', models.ImageField(blank=True, upload_to='tweetpics')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
